import type { WeaponId } from "../data/weapons";
import type { SkillId } from "../data/skills";
import type { Player } from "../entities/Player";
import type { BuildPathId } from "../data/buildPaths";
import type { EnemyId } from "../data/enemies";
import type { EvolutionId } from "../data/evolutions";

export type GameState = {
  player: Player;
  level: number;
  exp: number;
  expToNext: number;
  score: number;
  kills: number;
  elapsedSec: number;
  pausedForUpgrade: boolean;
  pausedForMenu: boolean;
  weaponLevels: Map<WeaponId, number>;
  evolvedWeapons: Map<WeaponId, EvolutionId>;
  skillLevels: Map<SkillId, number>;
  buildPathLevels: Map<BuildPathId, number>;
  startStyleId?: BuildPathId;
  unlockedSkills: Set<SkillId>;
  unlockedSkillsThisRun: Set<SkillId>;
  unlockedAchievements: Set<string>;
  evolvedArtsSeen: Set<EvolutionId>;
  standaloneSkillsSeen: Set<SkillId>;
  bossDefeats: Map<EnemyId, number>;
  highestDifficulty: number;
  selectedDifficulty: number;
  difficultyRewardMultiplier: number;
  rerolls: number;
  banishedUpgradeIds: Set<string>;
  banishCharges: number;
  renownTitle: string;
  devMode: {
    enabled: boolean;
    timeScale: number;
  };
};
